### ISSUE TITLE
ikadon修正

### ISSUE THREAD

**Issue by koba-lab** [koba-lab/mastodon#11]
メニューの下辺りの表示がちょっと崩れてる

![50fcde2ccc720421](https://user-images.githubusercontent.com/4122650/42743695-18a1446a-8901-11e8-93b4-a3e1e16e9f78.png)

* * * *

- [●] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [●] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by suzuki84g** [comment]
テーマをikadonに適用した状態でiOSのSafariから閲覧すると、上部のnavbarに該当する部分が正しく動作しない、という報告が上がっています。

[https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Customizing.md#multiple-themes](url)

https://github.com/koba-lab/mastodon/blob/8b843155466673e9f5a41b2d0e92352dae564fc0/app/javascript/styles/ikadon.scss#L1-L23

現状のコードでは個別に読み込ませに行ってますが、現在の`@application`で読み込ませるリストの方が多いので、漏れが出てるようです。defaultテーマで事象が起きないことも納得出来ます。
尚、MacOSのSafariでResponseさせても現状の事象が再発しませんでした。iOSに限られるようです。（Androidは未調査です）
実際にサーバ上げてiOSからアクセスさせなきゃテスト出来ないかなぁって思ってるんですが、他にテストの代替案あれば教えて下さい。正直変更内容と環境の構築が手間に乖離がありすぎて手が動かない…。

**Comment by koba-lab** [comment]
`メニューの下辺りの表示がちょっと崩れてる` の件に関しては取り込み済みなのでクローズします。
